/**
 * Amazon Bedrock Content Generation API for Footer About Section
 *
 * This API route uses Amazon Bedrock to generate compelling about content
 * for restaurant footers based on restaurant information from the database.
 */

import { NextResponse } from 'next/server';
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';
import OpenAI from 'openai';
import { VertexAI } from '@google-cloud/vertexai';

// Initialize Bedrock client
const bedrockClient = new BedrockRuntimeClient({
  region: process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId: 'bedrock-api-key',
    secretAccessKey: process.env.AWS_BEARER_TOKEN_BEDROCK || '',
  },
});

// Initialize OpenAI client
const openaiClient = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY || '',
});

interface GenerateContentRequest {
  restaurantName: string;
  restaurantType?: string; // e.g., "Italian Restaurant", "Fast Food", "Fine Dining"
  location?: string;
  specialties?: string[]; // e.g., ["Pizza", "Pasta", "Seafood"]
  tone?: 'professional' | 'casual' | 'elegant' | 'friendly';
  maxLength?: number; // Maximum character length (default: 200 for 2-liner)
  // Additional restaurant details from database table
  description?: string;
  cuisineTypes?: string[];
  priceRange?: string;
  established?: string;
  address?: string;
  city?: string;
  state?: string;
  country?: string;
}

interface GenerateContentResponse {
  success: boolean;
  content?: string;
  error?: string;
}

/**
 * Helper function to generate content using OpenAI as fallback
 * @param prompt - The prompt to send to OpenAI
 * @returns Generated content or null if failed
 */
async function generateContentWithOpenAI(prompt: string) {
  try {
    // Check if OpenAI is configured
    if (!process.env.OPENAI_API_KEY) {
      console.log('OpenAI API key not configured, skipping OpenAI fallback');
      return null;
    }

    const response = await openaiClient.chat.completions.create({
      model: process.env.OPENAI_MODEL || 'gpt-4-turbo',
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
      max_tokens: 150,
      temperature: 0.7,
    });

    const generatedText = response.choices[0]?.message?.content?.trim();
    if (!generatedText) {
      throw new Error('No content generated by OpenAI');
    }

    console.log('✅ Generated footer content using OpenAI fallback');
    return generatedText;

  } catch (error) {
    console.error('Error generating content with OpenAI:', error);
    return null;
  }
}

/**
 * POST endpoint to generate footer about content using Amazon Bedrock
 * Enhanced to accept restaurant table details for better content generation
 * Fallback sequence: Amazon Bedrock → OpenAI → Vertex AI
 */
export async function POST(request: Request) {
  try {
    const body: GenerateContentRequest = await request.json();

    // Validate required fields
    if (!body.restaurantName) {
      return NextResponse.json({
        success: false,
        error: 'Restaurant name is required',
      } as GenerateContentResponse, { status: 400 });
    }

    // Check if any AI provider is configured
    const hasBedrockConfig = !!process.env.AWS_BEARER_TOKEN_BEDROCK;
    const hasOpenAIConfig = !!process.env.OPENAI_API_KEY;
    const hasVertexConfig = !!process.env.GOOGLE_CLOUD_PROJECT_ID;

    if (!hasBedrockConfig && !hasOpenAIConfig && !hasVertexConfig) {
      return NextResponse.json({
        success: false,
        error: 'No AI provider configured (Bedrock, OpenAI, or Vertex AI)',
      } as GenerateContentResponse, { status: 500 });
    }

    const {
      restaurantName,
      restaurantType = 'restaurant',
      location = '',
      specialties = [],
      tone = 'professional',
      maxLength = 200,
      description = '',
      cuisineTypes = [],
      priceRange = '',
      established = '',
      address = '',
      city = '',
      state = '',
      country = '',
    } = body;

    // Build context for the AI prompt with restaurant details from database
    const contextParts = [];

    // Add restaurant type
    if (restaurantType) contextParts.push(`a ${restaurantType.toLowerCase()}`);

    // Add location information (use provided location or build from address fields)
    const locationInfo = location || [city, state, country].filter(Boolean).join(', ');
    if (locationInfo) contextParts.push(`located in ${locationInfo}`);

    // Add cuisine types if available
    if (cuisineTypes.length > 0) {
      contextParts.push(`serving ${cuisineTypes.join(' and ')} cuisine`);
    } else if (specialties.length > 0) {
      contextParts.push(`specializing in ${specialties.join(', ')}`);
    }

    // Add price range
    if (priceRange) contextParts.push(`${priceRange} price range`);

    // Add establishment year
    if (established) contextParts.push(`established in ${established}`);

    const context = contextParts.length > 0 ? ` - ${contextParts.join(', ')}` : '';

    // Create the prompt for content generation - optimized for 2-liner
    const prompt = `Generate a compelling and concise 2-line about section for a restaurant footer.

Restaurant Details:
- Name: ${restaurantName}${context}${description ? `\n- Description: ${description}` : ''}
- Tone: ${tone}
- Maximum length: ${maxLength} characters

Requirements:
- Write EXACTLY 2 sentences (2-liner)
- Use ${tone} tone
- Focus on what makes this restaurant special and unique
- Include key selling points (quality, service, experience, atmosphere)
- Keep it concise, engaging, and memorable
- Suitable for a website footer
- Do not include contact information, hours, or call-to-action
- Make it sound authentic and inviting
- Avoid generic phrases

Generate only the about text content (2 sentences), no additional formatting or explanations:`;

    let generatedContent = '';

    // Try Bedrock first
    if (hasBedrockConfig) {
      try {
        const modelId = 'global.anthropic.claude-sonnet-4-5-20250929-v1:0';
        const requestBody = {
          anthropic_version: 'bedrock-2023-05-31',
          max_tokens: 150,
          temperature: 0.7,
          messages: [{ role: 'user', content: prompt }],
        };

        const command = new InvokeModelCommand({
          modelId,
          body: JSON.stringify(requestBody),
          contentType: 'application/json',
          accept: 'application/json',
        });

        const response = await bedrockClient.send(command);
        const responseBody = JSON.parse(new TextDecoder().decode(response.body));

        if (!responseBody.content?.[0]?.text) {
          throw new Error('Invalid response from Bedrock model');
        }

        generatedContent = responseBody.content[0].text.trim();
      } catch (bedrockError) {
        console.error('Bedrock failed for footer content, trying OpenAI fallback:', bedrockError);
      }
    }

    // Fallback to OpenAI
    if (!generatedContent && hasOpenAIConfig) {
      try {
        console.log('Attempting OpenAI fallback for footer content generation...');
        const openaiResult = await generateContentWithOpenAI(prompt);
        
        if (openaiResult) {
          generatedContent = openaiResult;
        } else {
          throw new Error('No content generated by OpenAI');
        }
      } catch (openaiError) {
        console.error('OpenAI also failed for footer content, trying Vertex AI fallback:', openaiError);
      }
    }

    // Final fallback to Vertex AI
    if (!generatedContent && hasVertexConfig) {
      try {
        console.log('Attempting Vertex AI fallback for footer content generation...');
        let credentials: Record<string, any> | undefined;
        if (process.env.GOOGLE_CREDENTIALS_BASE64) {
          try {
            credentials = JSON.parse(Buffer.from(process.env.GOOGLE_CREDENTIALS_BASE64, 'base64').toString('utf-8'));
          } catch {
            console.error('Failed to parse GOOGLE_CREDENTIALS_BASE64');
          }
        }
        const vertexAI = new VertexAI({
          project: process.env.GOOGLE_CLOUD_PROJECT_ID!,
          location: process.env.GOOGLE_CLOUD_LOCATION || 'us-central1',
          googleAuthOptions: credentials ? { credentials } : undefined,
        });
        const model = vertexAI.getGenerativeModel({ model: process.env.VERTEX_AI_MODEL || 'gemini-2.5-pro' });

        const result = await model.generateContent({
          contents: [{ role: 'user', parts: [{ text: prompt }] }],
          generationConfig: { maxOutputTokens: 150, temperature: 0.7 },
        });

        const vertexText = result.response?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();
        if (vertexText) {
          generatedContent = vertexText;
          console.log('✅ Generated footer content using Vertex AI fallback');
        } else {
          throw new Error('No content generated by Vertex AI');
        }
      } catch (vertexError) {
        console.error('All AI providers failed for footer content:', vertexError);
      }
    }

    if (!generatedContent) {
      throw new Error('All AI providers (Bedrock, OpenAI, and Vertex AI) failed to generate content');
    }

    // Ensure content doesn't exceed max length
    if (generatedContent.length > maxLength) {
      // Truncate at the last complete sentence within the limit
      const truncated = generatedContent.substring(0, maxLength);
      const lastSentenceEnd = Math.max(
        truncated.lastIndexOf('.'),
        truncated.lastIndexOf('!'),
        truncated.lastIndexOf('?')
      );

      if (lastSentenceEnd > maxLength * 0.7) {
        generatedContent = truncated.substring(0, lastSentenceEnd + 1);
      } else {
        // If no good sentence break, truncate at last space
        const lastSpace = truncated.lastIndexOf(' ');
        generatedContent = lastSpace > 0 ? truncated.substring(0, lastSpace) + '...' : truncated + '...';
      }
    }

    return NextResponse.json({
      success: true,
      content: generatedContent,
    } as GenerateContentResponse);

  } catch (error) {
    console.error('Error generating footer content:', error);

    return NextResponse.json({
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate content',
    } as GenerateContentResponse, { status: 500 });
  }
}

/**
 * GET endpoint to check if the service is available
 */
export async function GET() {
  const hasBedrockConfig = !!process.env.AWS_BEARER_TOKEN_BEDROCK;
  const hasOpenAIConfig = !!process.env.OPENAI_API_KEY;
  const hasVertexConfig = !!process.env.GOOGLE_CLOUD_PROJECT_ID;
  
  const isConfigured = hasBedrockConfig || hasOpenAIConfig || hasVertexConfig;
  
  const configuredProviders = [];
  if (hasBedrockConfig) configuredProviders.push('Amazon Bedrock');
  if (hasOpenAIConfig) configuredProviders.push('OpenAI');
  if (hasVertexConfig) configuredProviders.push('Vertex AI');

  return NextResponse.json({
    success: true,
    available: isConfigured,
    providers: configuredProviders,
    message: isConfigured
      ? `Content generation service is available with: ${configuredProviders.join(', ')}`
      : 'No AI providers configured (Bedrock, OpenAI, or Vertex AI)',
  });
}
